<?php

namespace Database\Seeders;

use App\Models\DetailParameterLogsheet;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class DetailParameterLogsheetSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $detail = [
            [
                'detail_parameter' => 'Megawatt',
                'alarm' => null,
                'satuan' => 'MW',
                'parameter_logsheet_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'Mvar',
                'alarm' => null,
                'satuan' => 'Mvar',
                'parameter_logsheet_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'Power Factor',
                'alarm' => null,
                'satuan' => null,
                'parameter_logsheet_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'Voltage',
                'alarm' => null,
                'satuan' => 'KV',
                'parameter_logsheet_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'Frequency',
                'alarm' => null,
                'satuan' => 'Hz',
                'parameter_logsheet_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'TE 1421 temp.winding T1',
                'alarm' => '270',
                'satuan' => 'Deg F',
                'parameter_logsheet_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'TE 1422 temp.winding T2',
                'alarm' => '270',
                'satuan' => 'Deg F',
                'parameter_logsheet_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'TE 1423 temp.winding T3',
                'alarm' => '270',
                'satuan' => 'Deg F',
                'parameter_logsheet_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'SE 1800 NGG speed',
                'alarm' => null,
                'satuan' => 'Rpm',
                'parameter_logsheet_id' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'SE 1802 NPT speed',
                'alarm' => null,
                'satuan' => 'Rpm',
                'parameter_logsheet_id' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'PT 1804A comp.discharge press.',
                'alarm' => null,
                'satuan' => 'Psia',
                'parameter_logsheet_id' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'PT 1804B comp.discharge press.',
                'alarm' => null,
                'satuan' => 'Psia',
                'parameter_logsheet_id' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'TS.4 temp.exhaust',
                'alarm' => null,
                'satuan' => 'Deg F',
                'parameter_logsheet_id' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'TS.4 spread',
                'alarm' => null,
                'satuan' => 'Deg F',
                'parameter_logsheet_id' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'FCV 1202',
                'alarm' => null,
                'satuan' => '%',
                'parameter_logsheet_id' => '3',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'PT 1231 supply press.',
                'alarm' => '10',
                'satuan' => 'Psig',
                'parameter_logsheet_id' => '3',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'TE 1233 supply temp.',
                'alarm' => '140',
                'satuan' => 'Deg F',
                'parameter_logsheet_id' => '3',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'PDT 2020 filter d/p',
                'alarm' => '25',
                'satuan' => 'Psid',
                'parameter_logsheet_id' => '3',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'PT 12043 pump discharge press.',
                'alarm' => null,
                'satuan' => 'psig',
                'parameter_logsheet_id' => '3',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'FT 1247',
                'alarm' => null,
                'satuan' => 'Gpm',
                'parameter_logsheet_id' => '3',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'PT 1229 primary manifold press',
                'alarm' => null,
                'satuan' => 'Psig',
                'parameter_logsheet_id' => '3',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'LT 0001 reservoit level',
                'alarm' => '63/87',
                'satuan' => '%',
                'parameter_logsheet_id' => '4',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'PT 0026',
                'alarm' => '25',
                'satuan' => 'Psig',
                'parameter_logsheet_id' => '4',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'TE 1025',
                'alarm' => '160',
                'satuan' => 'Deg F',
                'parameter_logsheet_id' => '4',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'PDT 0015',
                'alarm' => null,
                'satuan' => 'Psid',
                'parameter_logsheet_id' => '4',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'TE 1036',
                'alarm' => '189',
                'satuan' => 'Deg F',
                'parameter_logsheet_id' => '4',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'TE 1035',
                'alarm' => '189',
                'satuan' => 'Deg F',
                'parameter_logsheet_id' => '4',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'LT1002',
                'alarm' => '45/85',
                'satuan' => '%',
                'parameter_logsheet_id' => '5',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'PDT 1006',
                'alarm' => '20',
                'satuan' => 'Psid',
                'parameter_logsheet_id' => '5',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'PDT 1121',
                'alarm' => '110',
                'satuan' => 'Psig',
                'parameter_logsheet_id' => '5',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'PDT 1007',
                'alarm' => null,
                'satuan' => 'Psid',
                'parameter_logsheet_id' => '5',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'PDT 1112',
                'alarm' => '8/16',
                'satuan' => 'Psig',
                'parameter_logsheet_id' => '5',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'TE 1128',
                'alarm' => '200',
                'satuan' => 'Deg F',
                'parameter_logsheet_id' => '5',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'TE 1123',
                'alarm' => '300',
                'satuan' => 'Deg F',
                'parameter_logsheet_id' => '5',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'TE 1124',
                'alarm' => '300',
                'satuan' => 'Deg F',
                'parameter_logsheet_id' => '5',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'TE 1125',
                'alarm' => '300',
                'satuan' => 'Deg F',
                'parameter_logsheet_id' => '5',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'TE 1126',
                'alarm' => '300',
                'satuan' => 'Deg F',
                'parameter_logsheet_id' => '5',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'TE 1127',
                'alarm' => '300',
                'satuan' => 'Deg F',
                'parameter_logsheet_id' => '5',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'XE 1805 A',
                'alarm' => '7',
                'satuan' => 'MIL',
                'parameter_logsheet_id' => '6',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'XE 1806 B',
                'alarm' => '7',
                'satuan' => 'MIL',
                'parameter_logsheet_id' => '6',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'XE 1806 A',
                'alarm' => '7',
                'satuan' => 'MIL',
                'parameter_logsheet_id' => '6',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'XE 1806 B',
                'alarm' => '7',
                'satuan' => 'MIL',
                'parameter_logsheet_id' => '6',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'XE 1807',
                'alarm' => '7',
                'satuan' => 'MIL',
                'parameter_logsheet_id' => '6',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'XE 1808',
                'alarm' => '7',
                'satuan' => 'MIL',
                'parameter_logsheet_id' => '6',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'XE 1809',
                'alarm' => '7',
                'satuan' => 'MIL',
                'parameter_logsheet_id' => '6',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'XE 1810',
                'alarm' => '7',
                'satuan' => 'MIL',
                'parameter_logsheet_id' => '6',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'PDT 4004',
                'alarm' => '5',
                'satuan' => 'inwg',
                'parameter_logsheet_id' => '7',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'PDT 4005',
                'alarm' => '5',
                'satuan' => 'inwg',
                'parameter_logsheet_id' => '7',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'TE 1401',
                'alarm' => '140',
                'satuan' => 'Deg F',
                'parameter_logsheet_id' => '7',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'TE 1466',
                'alarm' => '200',
                'satuan' => 'Deg F',
                'parameter_logsheet_id' => '7',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'PDT 4008',
                'alarm' => '2.75',
                'satuan' => 'inwg',
                'parameter_logsheet_id' => '7',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'PDT 4009',
                'alarm' => '2.76',
                'satuan' => 'inwg',
                'parameter_logsheet_id' => '7',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'TE 1430',
                'alarm' => '200',
                'satuan' => 'Deg F',
                'parameter_logsheet_id' => '7',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'detail_parameter' => 'TE 1431',
                'alarm' => '200',
                'satuan' => 'Deg F',
                'parameter_logsheet_id' => '7',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ]

        ];

        DetailParameterLogsheet::insert($detail);
    }
}
